pub const KERNEL_PID: u32 = 4;

pub const NDIS_DRIVER_BLOCK_NEXT_DRIVER: u64 = 0x08;
pub const NDIS_DRIVER_BLOCK_MINIPORT_QUEUE: u64 = 0x10;
pub const NDIS_DRIVER_BLOCK_DRIVER_OBJECT: u64 = 0x28;

pub const NDIS_MINIPORT_BLOCK_NEXT_MINIPORT: u64 = 0x08;
pub const NDIS_MINIPORT_BLOCK_IF_BLOCK: u64 = 0xFC8;
pub const NDIS_MINIPORT_BLOCK_PENDING_MAC: u64 = 0x14D4;

pub const NDIS_IF_BLOCK_ROD_OFFSET: u64 = 0x240;
pub const NDIS_ROD_IF_PHYS_ADDRESS: u64 = 0x224;
pub const NDIS_ROD_PERMANENT_PHYS_ADDRESS: u64 = 0x246;

pub const IF_BLOCK_IF_PHYS_ADDRESS: u64 = 0x464;
pub const IF_BLOCK_PERMANENT_PHYS_ADDRESS: u64 = 0x486;

pub const IF_PHYSICAL_ADDRESS_LENGTH: u64 = 0x00;
pub const IF_PHYSICAL_ADDRESS_ADDRESS: u64 = 0x02;

pub const MAC_ADDRESS_LENGTH: usize = 6;
pub const IF_PHYSICAL_ADDRESS_SIZE: usize = 34;

pub const DEVICE_OBJECT_NEXT_DEVICE: u64 = 0x10;
pub const DEVICE_OBJECT_DRIVER_OBJECT: u64 = 0x08;
pub const DRIVER_OBJECT_DEVICE_OBJECT: u64 = 0x08;
